#!/bin/bash
# 🚀 Complete Guide: How to Run Sustainability Analysis

echo "🌱 How to Run Sustainability Analysis - Complete Guide"
echo "===================================================="
echo ""

echo "🎯 You have 4 ways to run the sustainability analysis:"
echo ""

# Option 1: Local Testing (Immediate)
echo "1️⃣  LOCAL TESTING (Run Now - 2 minutes)"
echo "======================================="
echo "   Test the analysis on your local machine:"
echo ""
echo "   📂 Change to project directory:"
echo "   cd /Users/159645/Meena/Projects/vibe-coding/Tracker"
echo ""
echo "   🚀 Run local pipeline test:"
echo "   ./sustainability-analyzer/test-pipeline.sh"
echo ""
echo "   📊 View visual dashboard:"
echo "   open sustainability-analyzer/pipeline-test-output/dashboard.html"
echo ""
echo "   ✨ This generates demo reports with sample data!"
echo ""

# Option 2: Azure DevOps Pipeline (Recommended)
echo "2️⃣  AZURE DEVOPS PIPELINE (Recommended Production Method)"
echo "========================================================"
echo ""
echo "   Step A: Create Pipeline in Azure DevOps Portal"
echo "   ---------------------------------------------"
echo "   1. Go to Azure DevOps → Pipelines → New Pipeline"
echo "   2. Select your repository source (GitHub/Azure Repos)"
echo "   3. Choose 'Existing Azure Pipelines YAML file'"
echo "   4. Select: azure-pipelines.yml"
echo "   5. Click 'Run'"
echo ""
echo "   Step B: Configure Variables (Optional)"
echo "   ------------------------------------"
echo "   • Go to Pipeline → Edit → Variables"
echo "   • Add: sustainabilityThreshold = 75"
echo "   • Add: TeamsWebhookUrl = <your-webhook>"
echo ""
echo "   Step C: Pipeline Runs Automatically On:"
echo "   -------------------------------------"
echo "   ✅ Push to main/develop branches"
echo "   ✅ Pull requests"
echo "   ✅ Weekly schedule (Monday 2 AM UTC)"
echo "   ✅ Manual triggers"
echo ""

# Option 3: Azure CLI (Command Line)
echo "3️⃣  AZURE CLI (Command Line Method)"
echo "==================================="
echo ""
echo "   📋 Prerequisites:"
echo "   • Install Azure CLI: brew install azure-cli"
echo "   • Login: az login"
echo "   • Set project: az devops configure --defaults organization=<org> project=<project>"
echo ""
echo "   🔨 Create Pipeline:"
echo "   az pipelines create \\"
echo "     --name \"Sustainability-Analysis\" \\"
echo "     --description \"Code sustainability evaluation\" \\"
echo "     --repository Tracker \\"
echo "     --branch main \\"
echo "     --yaml-path azure-pipelines.yml"
echo ""
echo "   ▶️  Run Pipeline:"
echo "   az pipelines run --name \"Sustainability-Analysis\""
echo ""
echo "   📊 Check Results:"
echo "   az pipelines runs list --top 1"
echo ""

# Option 4: Manual Analysis (Advanced)
echo "4️⃣  MANUAL ANALYSIS (Advanced/Custom)"
echo "===================================="
echo ""
echo "   Run individual components manually:"
echo ""
echo "   🔍 Core Analysis:"
echo "   python3 sustainability-analyzer/analyzer/sustainability_analyzer.py \\"
echo "     --path . \\"
echo "     --output analysis.json \\"
echo "     --format json"
echo ""
echo "   🎨 Generate Visual Dashboard:"
echo "   python3 sustainability-analyzer/dashboard/visual_dashboard_generator.py \\"
echo "     --input analysis.json \\"
echo "     --output dashboard.html"
echo ""
echo "   📋 Generate Data Tables:"
echo "   python3 sustainability-analyzer/dashboard/data_tables_generator.py \\"
echo "     --input analysis.json \\"
echo "     --output tables.html"
echo ""

echo "🎊 WHAT YOU GET FROM EACH METHOD:"
echo "================================="
echo ""
echo "📊 Generated Reports:"
echo "   • Interactive Visual Dashboard with charts"
echo "   • Advanced Data Tables with filtering/export"
echo "   • Executive Summary PDF"
echo "   • Raw JSON analysis data"
echo ""
echo "🎯 Key Metrics Analyzed:"
echo "   • Overall Sustainability Score (/100)"
echo "   • Energy Efficiency (/100)"
echo "   • Resource Utilization (/100)"
echo "   • Carbon Footprint (/100)"
echo "   • Performance Optimization (/100)"
echo "   • Sustainable Practices (/100)"
echo ""
echo "✅ Quality Gates:"
echo "   • Pass/Fail based on thresholds"
echo "   • Automated recommendations"
echo "   • Issue identification and fixes"
echo ""

echo "🚀 QUICK START RECOMMENDATION:"
echo "=============================="
echo ""
echo "👉 START HERE (Takes 2 minutes):"
echo ""
echo "   1. Test locally first:"
echo "      ./sustainability-analyzer/test-pipeline.sh"
echo ""
echo "   2. View the results:"
echo "      open sustainability-analyzer/pipeline-test-output/index.html"
echo ""
echo "   3. Then set up Azure DevOps pipeline for production"
echo ""
echo "🎯 This gives you immediate results and shows exactly"
echo "   what the pipeline will generate!"
echo ""

echo "📚 DOCUMENTATION:"
echo "================="
echo "   📖 Setup Guide: sustainability-analyzer/PIPELINE_SETUP.md"
echo "   🚀 Quick Start: sustainability-analyzer/PIPELINE_QUICKSTART.md"
echo "   🧪 Local Demo: sustainability-analyzer/dashboard/demo_output/"
echo ""

echo "✨ Ready to run sustainability analysis!"
echo "   Choose your preferred method above and get started! 🌱"