#!/bin/bash
# 🚀 Quick Start Guide for Sustainability Dashboard

echo "🌱 Sustainability Analysis Dashboard - Quick Start"
echo "================================================="
echo ""
echo "📊 Generated Files:"
echo "  ✅ Visual Dashboard:     visual_dashboard.html"
echo "  ✅ Interactive Tables:   data_tables.html" 
echo "  ✅ Navigation Index:     index.html"
echo "  ✅ Raw Data:            demo_analysis.json"
echo ""
echo "🌐 To view the dashboard:"
echo "  1. Navigate to: $(pwd)/demo_output/"
echo "  2. Open index.html in your web browser"
echo "  3. Or run: open demo_output/index.html"
echo ""
echo "📋 What's Included:"
echo "  📊 Visual Dashboard - Interactive charts with:"
echo "      • Radar charts for sustainability metrics"
echo "      • Bar charts for performance comparison"
echo "      • Gauge charts for overall scoring"
echo "      • 3D scatter plots for trend analysis"
echo "      • Pie charts for language distribution"
echo ""
echo "  📋 Data Tables - Advanced tables with:"
echo "      • Sortable and filterable data"
echo "      • Export to CSV, Excel, PDF"
echo "      • Search and pagination"
echo "      • Detailed metrics breakdown"
echo ""
echo "  📄 Summary Report - Executive overview with:"
echo "      • Key sustainability metrics"
echo "      • Issues and recommendations"
echo "      • Project statistics"
echo "      • Next steps and actions"
echo ""
echo "🎯 Key Features:"
echo "  • Overall Sustainability Score: 78.5/100"
echo "  • 25 files analyzed across 4 languages"
echo "  • 3 issues identified with solutions"
echo "  • 3 optimization recommendations"
echo ""
echo "🚀 Try Again Options:"
echo "  • Run: python3 run_demo.py (regenerate demo)"
echo "  • Run: python3 visual_dashboard_generator.py --input demo_analysis.json"
echo "  • Run: python3 data_tables_generator.py --input demo_analysis.json"
echo ""
echo "✨ Ready to explore your sustainability insights!"